services:
    web:
      build:
        context: ./
        target: dev
      volumes:
        - .:/src
      command: npm run dev
      ports: 
        - "8000:8000"
      environment:
        NODE_ENV: development
      networks: 
        - default
    mysql5.6:
      # 镜像名
      image: mysql:5.6
      command: [ #使用 command 可以覆盖容器启动后默认执行的命令
        '--character-set-server=utf8mb4', #设置数据库表的数据集
        '--collation-server=utf8mb4_unicode_ci', #设置数据库表的数据集
      ]

      # 容器名(以后的控制都通过这个)
      container_name: mysql5.6
      # 重启策略
      restart: always
      environment:
        # 时区上海
        TZ: Asia/Shanghai
        # root 密码
        MYSQL_ROOT_PASSWORD: root
        # 初始化数据库(后续的初始化sql会在这个库执行)
        MYSQL_DATABASE: express
        # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
        MYSQL_USER: express
        # 用户密码
        MYSQL_PASSWORD: express
        # 映射端口
      ports:
        - 3308:3306
      volumes:
        # 数据挂载
        - ./mysql/data/:/var/lib/mysql/
        # 配置挂载
        - ./mysql/conf/:/etc/mysql/conf.d/
        # 初始化目录挂载，注意此处我只跑了这个挂载，只是为了说明其他配置不应该数据初始化
        - ./mysql/init/:/docker-entrypoint-initdb.d/
      networks: 
        - default
networks:
    default:
      driver: bridge
      ipam:
        driver: default

